# need 4 gpus

project: coconut
save_path: output
name: gsm-coconut-embds-weight_0.1

only_eval: False

coconut_embds: True
embedding_loss_weight: 0.1

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: 
seed: 0
resume: 3
bf16: False
train_path: data/gsm_train.jsonl
val_path: data/gsm_valid.json
reset_optimizer: True
batch_size_training: 32
debug: False
use_wandb: False
gradient_accumulation_steps: 1
num_epochs: 25
lr: !!float "1e-4"
weight_decay: 0.01